# Generated by Django 4.2.2 on 2023-07-06 00:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='phone', max_length=50)),
                ('birth_date', models.DateField(default=datetime.datetime.now)),
                ('gender', models.CharField(max_length=20)),
                ('user_type', models.CharField(default='user', max_length=255)),
                ('profile_picture', models.ImageField(null=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(null=True, upload_to='')),
                ('certificate', models.ImageField(null=True, upload_to='certificates/')),
                ('specialty', models.CharField(max_length=50)),
                ('office_location', models.CharField(blank=True, default='office', max_length=100, null=True)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('phone', models.CharField(default='phone', max_length=50)),
                ('birth_date', models.DateField(default=datetime.datetime.now)),
                ('gender', models.CharField(max_length=50)),
                ('user_type', models.CharField(default='doctor', max_length=255)),
                ('about', models.TextField(blank=True, max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_reservations', to='users.person')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_reservations', to='users.person')),
            ],
            options={
                'unique_together': {('doctor', 'date')},
            },
        ),
    ]
