# Generated by Django 4.2.2 on 2023-06-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_doctor_person_remove_person_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='user_type',
            field=models.CharField(default='doctor'),
        ),
        migrations.AddField(
            model_name='person',
            name='user_type',
            field=models.CharField(default='user'),
        ),
    ]
