# Generated by Django 4.2.2 on 2023-06-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_doctor_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='friends',
            field=models.ManyToManyField(blank=True, to='users.doctor'),
        ),
        migrations.AddField(
            model_name='person',
            name='friends',
            field=models.ManyToManyField(blank=True, to='users.person'),
        ),
    ]
