# Generated by Django 4.2.2 on 2023-06-30 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_doctor_friends_remove_person_friends_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
