# Generated by Django 4.1.5 on 2023-07-01 16:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_reservation"),
        ("users", "0008_delete_user"),
    ]

    operations = []
