# Generated by Django 4.1.5 on 2023-07-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_merge_0006_reservation_0008_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="user_type",
            field=models.CharField(default="doctor", max_length=255),
        ),
        migrations.AlterField(
            model_name="person",
            name="user_type",
            field=models.CharField(default="user", max_length=255),
        ),
    ]
