# Generated by Django 4.1.5 on 2023-07-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_alter_doctor_gender_alter_doctor_specialty"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="about",
            field=models.TextField(default="a", max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="doctor",
            name="profile_picture",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="person",
            name="profile_picture",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
