# Generated by Django 4.2.2 on 2023-07-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_doctor_gender_alter_doctor_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='about',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='doctor',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='person',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
