# Generated by Django 4.1.5 on 2023-07-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="post",
            name="like",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
